### ISSUE TITLE
Error thrown when getting location on some devices

### ISSUE THREAD

**Issue by iqfareez** [iqfareez/app_waktu_solat_malaysia#56]
As per Nasir Othman's email:
```
<---------Debug log:---------------

                            ----------------------APP--------------------------
                        Version: 1.15.94, VersionCode: 47
                        ---------------------DEVICE---------------------
                        Android 5.1.1 (SDK 22), OPPO A37fw
                        Hardware: qcom
                        Screen size (360.0, 640.0) DiP
                        PixRatio 2.0

                        Last prayer api called: https://mpt.i906.my/api/prayer/jhr-7 ,
                        Location get: PlatformException(error, Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference
at c.a.a.c.b()
at c.a.a.c.onMethodCall()
at e.a.c.a.j$a.a()
at io.flutter.embedding.engine.e.b.a()
at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage()
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:150)
at android.os.Looper.loop(Looper.java:139)
at android.app.ActivityThread.main(ActivityThread.java:5541)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
) ,
                   
    ------------------EO🐛---------------->
```

This issue is reproduceable on Android Emulator SDK 30.

**Comment by iqfareez** [comment]
I can reproduce this issue on my device. I can conclude that the error occur when:
- Device didn't have **gps** coordinate yet when Geocoding method is called.
- GPS is turned **off**.

![Screenshot_20210329-083734.jpg](https://user-images.githubusercontent.com/60868965/112773907-780d4200-906a-11eb-9fe5-16cf9358e2d9.jpg)

**Comment by iqfareez** [comment]
Hm. Dah lama tk nmpak error ni. Plugin dah fix barangkali. Closing this for now. Submit new issue if occur again.
